import type { ChinguCardPropsType } from "./ChinguCard";

export const mockData: ChinguCardPropsType[] = [
  {
    gender: "male",
    countryName: "United States",
    countryCode: "US",
    roleType: "Web",
    voyageRole: "Developer",
    soloProjectTier: "Tier 2",
    voyageTier: "Tier 1",
    voyageNum: "V58",
    timestamp: "2023-09-12",
  },
  {
    gender: "female",
    countryName: "Canada",
    countryCode: "CA",
    roleType: "",
    voyageRole: "Scrum Master",
    soloProjectTier: "Tier 1",
    voyageTier: "Tier 2",
    voyageNum: "V58",
    timestamp: "2022-05-03",
  },
  {
    gender: "non-binary",
    countryName: "Germany",
    countryCode: "DE",
    roleType: "Python",
    voyageRole: "Developer",
    soloProjectTier: "Tier 3",
    voyageTier: "Tier 1",
    voyageNum: "V57",
    timestamp: "2021-11-22",
  },
  {
    gender: "female",
    countryName: "Brazil",
    countryCode: "BR",
    roleType: "",
    voyageRole: "UI/UX Designer",
    soloProjectTier: "Tier 1",
    voyageTier: "Tier 3",
    voyageNum: "V56",
    timestamp: "2020-07-19",
  },
  {
    gender: "male",
    countryName: "India",
    countryCode: "IN",
    roleType: "",
    voyageRole: "Product Owner",
    soloProjectTier: "Tier 2",
    voyageTier: "Tier 2",
    voyageNum: "V59",
    timestamp: "2024-01-29",
  },
];
