import type { ChinguCardPropsType } from "./ChinguCard";

export const mockData: ChinguCardPropsType[] = [
  {
    gender: "male",
    countryName: "United States",
    countryCode: "US",
    roleType: "Web",
    voyageRole: "Developer",
    soloProjectTier: "Tier 2",
    voyageTier: "Tier 1",
    voyageNum: "58",
    timestamp: "2023-09-12",
  },
  {
    gender: "female",
    countryName: "Canada",
    countryCode: "CA",
    roleType: "Data",
    voyageRole: "Scrum Master",
    soloProjectTier: "Tier 1",
    voyageTier: "Tier 2",
    voyageNum: "58",
    timestamp: "2022-05-03",
  },
  {
    gender: "non-binary",
    countryName: "Germany",
    countryCode: "DE",
    roleType: "Python",
    voyageRole: "Developer",
    soloProjectTier: "Tier 3",
    voyageTier: "Tier 1",
    voyageNum: "57",
    timestamp: "2021-11-22",
  },
  {
    gender: "female",
    countryName: "Brazil",
    countryCode: "BR",
    roleType: "Web",
    voyageRole: "UI/UX Designer",
    soloProjectTier: "Tier 1",
    voyageTier: "Tier 3",
    voyageNum: "56",
    timestamp: "2020-07-19",
  },
  {
    gender: "male",
    countryName: "India",
    countryCode: "IN",
    roleType: "Web",
    voyageRole: "Product Owner",
    soloProjectTier: "Tier 2",
    voyageTier: "Tier 2",
    voyageNum: "59",
    timestamp: "2024-01-29",
  },
  {
    gender: "female",
    countryName: "Spain",
    countryCode: "ES",
    roleType: "Web",
    voyageRole: "Developer",
    soloProjectTier: "Tier 3",
    voyageTier: "Tier 1",
    voyageNum: "55",
    timestamp: "2019-04-10",
  },
  {
    gender: "male",
    countryName: "United Kingdom",
    countryCode: "UK",
    roleType: "Data",
    voyageRole: "Product Owner",
    soloProjectTier: "Tier 2",
    voyageTier: "Tier 3",
    voyageNum: "60",
    timestamp: "2024-07-21",
  },
  {
    gender: "non-binary",
    countryName: "Netherlands",
    countryCode: "NL",
    roleType: "Web",
    voyageRole: "Scrum Master",
    soloProjectTier: "Tier 1",
    voyageTier: "Tier 1",
    voyageNum: "58",
    timestamp: "2023-03-18",
  },
  {
    gender: "female",
    countryName: "France",
    countryCode: "FR",
    roleType: "Python",
    voyageRole: "Developer",
    soloProjectTier: "Tier 2",
    voyageTier: "Tier 2",
    voyageNum: "57",
    timestamp: "2022-09-30",
  },
  {
    gender: "male",
    countryName: "Australia",
    countryCode: "AU",
    roleType: "Web",
    voyageRole: "UI/UX Designer",
    soloProjectTier: "Tier 3",
    voyageTier: "Tier 1",
    voyageNum: "54",
    timestamp: "2021-01-14",
  },
  {
    gender: "female",
    countryName: "Hungary",
    countryCode: "HU",
    roleType: "Web",
    voyageRole: "Developer",
    soloProjectTier: "Tier 1",
    voyageTier: "Tier 2",
    voyageNum: "59",
    timestamp: "2024-02-11",
  },
  {
    gender: "male",
    countryName: "Poland",
    countryCode: "PL",
    roleType: "Data",
    voyageRole: "Scrum Master",
    soloProjectTier: "Tier 1",
    voyageTier: "Tier 1",
    voyageNum: "56",
    timestamp: "2018-08-07",
  },
  {
    gender: "female",
    countryName: "Japan",
    countryCode: "JP",
    roleType: "Web",
    voyageRole: "Developer",
    soloProjectTier: "Tier 3",
    voyageTier: "Tier 3",
    voyageNum: "58",
    timestamp: "2023-05-13",
  },
  {
    gender: "non-binary",
    countryName: "Sweden",
    countryCode: "SE",
    roleType: "Python",
    voyageRole: "Product Owner",
    soloProjectTier: "Tier 2",
    voyageTier: "Tier 1",
    voyageNum: "57",
    timestamp: "2021-11-02",
  },
  {
    gender: "male",
    countryName: "South Africa",
    countryCode: "ZA",
    roleType: "Web",
    voyageRole: "UI/UX Designer",
    soloProjectTier: "Tier 1",
    voyageTier: "Tier 2",
    voyageNum: "55",
    timestamp: "2019-12-19",
  },
  {
    gender: "female",
    countryName: "Italy",
    countryCode: "IT",
    roleType: "Web",
    voyageRole: "Developer",
    soloProjectTier: "Tier 3",
    voyageTier: "Tier 1",
    voyageNum: "60",
    timestamp: "2024-03-20",
  },
  {
    gender: "male",
    countryName: "Mexico",
    countryCode: "MX",
    roleType: "Data",
    voyageRole: "Scrum Master",
    soloProjectTier: "Tier 2",
    voyageTier: "Tier 3",
    voyageNum: "58",
    timestamp: "2023-06-28",
  },
  {
    gender: "female",
    countryName: "Norway",
    countryCode: "NO",
    roleType: "Web",
    voyageRole: "Product Owner",
    soloProjectTier: "Tier 1",
    voyageTier: "Tier 2",
    voyageNum: "57",
    timestamp: "2021-10-05",
  },
  {
    gender: "non-binary",
    countryName: "Argentina",
    countryCode: "AR",
    roleType: "Web",
    voyageRole: "Developer",
    soloProjectTier: "Tier 3",
    voyageTier: "Tier 1",
    voyageNum: "56",
    timestamp: "2020-03-17",
  },
  {
    gender: "female",
    countryName: "Denmark",
    countryCode: "DK",
    roleType: "Web",
    voyageRole: "Developer",
    soloProjectTier: "Tier 2",
    voyageTier: "Tier 2",
    voyageNum: "59",
    timestamp: "2024-02-14",
  }
];

